site_name: McDic's Blog
site_url: https://blog.mcdic.net/

theme:
  name: material
  features:
    - search.suggest
    - search.highlight

plugins:
  - tags
  - blog:
      blog_dir: .
      blog_toc: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
  - search

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/
# Intentionally added features:
# - Admonitions
# - Annotations
# - Buttons
# - Code Blocks
# - Data Tables
# - Footnotes
# - Grid
# - Icons and Emojis
# - Images
# - Lists
# - Math
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
