site_name: McDic's Blog
site_url: "https://blog.mcdic.net"
site_author: "Minsung Kim (McDic)"
site_description: "McDic's Personal Blog"

repo_url: "https://github.com/McDic/BlogV2"
repo_name: "McDic/BlogV2"
remote_branch: deploy
strict: true

theme:
  logo: assets/images/mcdic.jpg
  favicon: assets/images/favicon.ico
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.code.copy
  custom_dir: overrides
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - index.md
  - Architecture: architecture.md
  - Post Format: format.md
  - AI Songs: ai_songs.md
  - About: about.md
  - AMA: ama.md

plugins:
  - tags
  - rss:
      enabled: false
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - search
  - mcdic:
      enabled: true
      post_views:
        forced_update: false
      git_dates:
        format: "%b %d, %Y"
      historical_batch: 10
      sorted:
        recent: 20
        most_viewed: 20
  - git-revision-date-localized:
      enabled: false
      enable_creation_date: true
      type: iso_datetime
      timezone: Asia/Seoul
  - glightbox

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/autoscroll.js
  - https://w.soundcloud.com/player/api.js
  - javascripts/musicplayer.js

extra_css:
  - stylesheets/admonitions.css
  - stylesheets/extra.css
  - stylesheets/footer.css
  - stylesheets/404.css
  - stylesheets/meta.css
  - stylesheets/header.css
  - stylesheets/article.css

extra:
  analytics:
    provider: google
    property: G-LNQJ79T5LM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/McDic
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mcdic/
    - icon: custom/codeforces
      link: https://codeforces.com/profile/McDic
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/mcdic

copyright: Every article in this blog is owned by Minsung Kim and licensed by CC BY-NC 4.0 DEED.
