name: Deploying Blog

on:
  push:
    branch:
      - master
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      - run: pip install -r requirements.txt
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Deploy Blog
        run: mkdocs gh-deploy -v -r origin -b deploy -s --force --no-history

  post-processing:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        name: Checkout to deploy branch
        with:
          ref: deploy
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Add CNAME manually
        run: |
          if [ ! -f CNAME ];
            then echo "blog.mcdic.net" >> CNAME
            git add CNAME
          fi
      - name: Commit and push
        run: |
          if [[ `git status --porcelain` ]]; then
            git commit -m "Post-processed a build via Github Action"
            git push
          fi
