name: Linting with pre-commit

on:
  push:
    branches:
      - "**"
      - "!deploy"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
      - "!deploy"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
      - name: Execute pre-commit
        uses: pre-commit/action@v2.0.3
